version: '3'

services:
  nasm_ubuntu:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nasm_ubuntu
    command: tail -f /dev/null
    volumes:
      - assembly-programs:/programs/assembly-programs
      - ./assembly-programs:/programs/assembly-programs

volumes:
  assembly-programs: